# AMZMALL_DEV_GITOPS/values.yaml

replicaCount: 2

image:
  repository: 009946608368.dkr.ecr.ap-northeast-2.amazonaws.com/amzdraw-dev
  pullPolicy: IfNotPresent
  # 이미지 태그를 지정 비워두면 Chart.yaml의 appVersion을 사용
  tag: 2024-02-15T03-03-58

imagePullSecrets:
  - name: ecr-secret

service:
  type: NodePort
  port: 8080
  # NodePort 서비스를 사용할 때 외부에 노출할 포트 번호를 지정
  nodePort: 30007

nodeSelector:
  # Name: "service_node_group"
  eks.amazonaws.com/nodegroup: "service_node_group-20240218121856709200000003"
# 각 Pod가 최소 64MiB의 메모리와 250m CPU를 요청, 최대 128MiB의 메모리와 500m CPU까지 사용할 수 있음
#  여기서 'm'은 밀리코어를 의미하며, 1000m은 1 vCPU/core
# resources:
#   requests:
#     memory: "64Mi"
#     cpu: "250m"
#   limits:
#     memory: "128Mi"
#     cpu: "500m"

tolerations: []

affinity: {}