# AMZMALL_DEV_GITOPS/backend/values.yaml

replicaCount: 2

image:
  repository: 009946608368.dkr.ecr.ap-northeast-2.amazonaws.com/amzdraw-dev
  pullPolicy: IfNotPresent
  tag: 2024-03-27T16-09-39

imagePullSecrets:
  - name: ecr-secret

service:
  type: NodePort
  port: 8080
  nodePort: 30007

nodeSelector:
  node_group: "service_node_group"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 50
  targetCPUUtilizationPercentage: 60

resources:
  requests:
    cpu: "500m"
    memory: "1024Mi"
  limits:
    cpu: "800m"
    memory: "2048Mi"
