# AMZMALL_DEV_GITOPS/backend/values.yaml

replicaCount: 2

image:
  repository: 009946608368.dkr.ecr.ap-northeast-2.amazonaws.com/amzdraw-dev
  pullPolicy: IfNotPresent
  tag: 2024-03-19T16-02-37

imagePullSecrets:
  - name: ecr-secret

service:
  type: NodePort
  port: 8080
  nodePort: 30007

nodeSelector:
  node_group: "service_node_group"

hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 30

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "512Mi"
