# AMZMALL_DEV_GITOPS/tempaltes/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "amzmall.fullname" . }}
  labels:
    {{- include "amzmall.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "amzmall.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "amzmall.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP