apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "amzdraw.fullname" . }}
  labels:
    {{- include "amzdraw.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "amzdraw.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "amzdraw.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: DB_PASSWORD
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: DB_URL
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: DB_USER
            - name: TOSS_CLIENT_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: TOSS_CLIENT_KEY
            - name: TOSS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: TOSS_SECRET_KEY
