# AMZDRAW_DEV_GITOPS/backend/templates/hpa.yaml

# Horizontal Pod Autoscaler(HPA) 설정이 활성화되었는지 확인하는 조건문
{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2                         # HPA의 API 버전을 지정
kind: HorizontalPodAutoscaler                       # Kubernetes 리소스 종류를 HPA로 지정
metadata:
  name: {{ include "amzdraw.fullname" . }}          # HPA의 이름을 설정 헬름 템플릿 함수를 사용하여 이름을 동적으로 결정
  labels:
    {{- include "amzdraw.labels" . | nindent 4 }}   # HPA에 적용할 라벨을 설정. 헬름 템플릿 함수를 사용
spec:
  scaleTargetRef:                                   # HPA가 대상으로 하는 리소스 지정
    apiVersion: apps/v1                             # 대상 리소스의 API 버전
    kind: Deployment                                # 대상 리소스의 종류
    name: {{ include "amzdraw.fullname" . }}        # 대상 리소스의 이름, 헬름 템플릿 함수 사용
  minReplicas: {{ .Values.hpa.minReplicas }}        # 최소 복제본(replica) 수를 지정. values.yaml 파일에서 설정값 호출
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:                                          # HPA가 스케일링을 결정하는 데 사용할 메트릭 지정
    - type: Resource                                # 메트릭의 유형을 리소스로 지정
      resource:
        name: cpu                                   # CPU 사용량을 기준으로 스케일링을 결정
        target:                                     # 스케일링의 목표 값을 설정
          type: Utilization                         # 스케일링의 목표 유형을 CPU 사용률로 설정
          averageUtilization: {{ .Values.hpa.targetCPUUtilizationPercentage }} # CPU 평균 사용률 목표치를 지정. values.yaml 파일에서 설정값 호출
{{- end }}
