 # AMZDRAW_DEV_GITOPS/backend/tempaltes/ingress.yaml

# 예상 시나리오
# 1.사용자가 HTTP를 통해 웹사이트에 접속
  # 1-1) 사용자가 브라우저에서 http://www.amzdraw.shop을 입력하고 웹사이트에 접속

# 2. ALB가 HTTP 리스너를 통해 요청을 수신
  # 2-1) ALB에는 80 포트(HTTP) 리스너가 설정되어 있으며, 사용자의 요청을 받는다

# 3.ALB는 요청을 HTTPS로 리다이렉션
  # 3-1) ALB는 alb.ingress.kubernetes.io/actions.ssl-redirect 어노테이션에 정의된 규칙에 따라 
  # 3-2) 사용자의 HTTP 요청은 301 Moved Permanently 상태 코드와 함께 HTTPS URL(https://www.amzdraw.shop)로 리다이렉션

# 4. 사용자의 브라우저가 리다이렉션을 따릅니다:
  # 4-1) 브라우저는 ALB로부터 받은 리다이렉션 응답을 처리하고, 자동으로 https://www.amzdraw.shop으로 새 요청

# 5. ALB가 HTTPS 리스너를 통해 새 요청을 수신
  # 5-1) 이번에는 ALB의 443 포트(HTTPS) 리스너가 사용자의 요청을 받습니다. 
  # 5-2) ALB는 alb.ingress.kubernetes.io/certificate-arn 어노테이션에 지정된 ACM에서 발급한 SSL/TLS 인증서를 사용하여 요청을 암호화

# 6. ALB는 인증서를 사용해 요청을 암호화하고 백엔드로 전달
  # 6-1) ACM에서 발급한 SSL/TLS 인증서를 사용하여 요청을 암호화하고,
  # 6-2) 설정된 백엔드 서비스(예: amzdraw.fullname 서비스)로 전달
  # 6-3) 이 경우, 서비스는 내부적으로 8080 포트를 사용하여 트래픽을 처리

# 최종 결과 - 사용자는 보안된 연결을 통해 웹사이트에 접속합니다:
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "amzdraw.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-northeast-2:009946608368:certificate/f44c8be0-432d-4e90-934a-aa3d768c9ace"
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": {"Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'

spec:
  rules:
  - host: "www.amzdraw.shop"
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: ssl-redirect
            port:
              name: use-annotation
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ include "amzdraw.fullname" . }}
            port:
              number: 8080

