apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: karpenter-provisioner
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
    - key: kubernetes.io/arch
      operator: In
      values:
        - amd64
  limits:
    resources:
      cpu: '1'
  providerRef:
    name: default
  ttlSecondsAfterEmpty: 30