apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
    - key: kubernetes.io/arch
      operator: In
      values:
        - amd64
    - key: "node_group"
      operator: "In"
      values: ["service_node_group"]
  limits:
    resources:
      cpu: '1'
  providerRef:
    name: default
  ttlSecondsAfterEmpty: 30